### ISSUE TITLE
Can not use the AND clause on WHERE in bean-query

### ISSUE THREAD

**Issue by fernandodeperto** [beancount/beancount#1]
I've been adopting beancount for my accounting and it's great. I'm using the Fava UI, which already gives me 80% of what I want in terms of reports. For the remaining, I'm trying to use bean-query but I've had some problems.

This issue is related to this example in the beancount doc:
```
SELECT date, payee 
WHERE account ~ 'Expenses:Food:Restaurant' 
  AND ‘trip-new-york’ IN tags
  AND NOT payee = 'Uncle Boons'
````

I would like to things that are similar to this example. So let's do a simple one. First, only one clause works:
```
beancount> select date, payee where 'presente' in tags
   date         payee     
---------- ---------------
2017-04-27 Carre Asiatique
2017-04-27 Carre Asiatique
```

The other clause also works:
```
beancount> select date, payee where payee ~ 'Carre'
   date         payee     
---------- ---------------
2017-04-27 Carre Asiatique 
```

But when I try to use the ```AND``` clause:
```
beancount> select date, payee where 'presente' in tags and payee ~ 'Carre'
Traceback (most recent call last):
  File "/usr/lib/python3.6/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'BQLShell' object has no attribute 'do_select'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/beancount/query/shell.py", line 258, in run_parser
    self.dispatch(statement)
  File "/usr/lib/python3.6/site-packages/beancount/query/shell.py", line 238, in dispatch
    return method(statement)
  File "/usr/lib/python3.6/site-packages/beancount/query/shell.py", line 404, in on_Select
    self.options_map)
  File "/usr/lib/python3.6/site-packages/beancount/query/query_execute.py", line 232, in execute_query
    if c_where is None or c_where(context):
  File "/usr/lib/python3.6/site-packages/beancount/query/query_compile.py", line 175, in __call__
    arg_right = self.right(context)
  File "/usr/lib/python3.6/site-packages/beancount/query/query_compile.py", line 115, in __call__
    return self.operator(self.left(context), self.right(context))
TypeError: unsupported operand type(s) for &: 'frozenset' and 'bool'
```

Am I doing something wrong?

**Comment by fernandodeperto** [comment]
It was after adding the issue that I saw that you already use the issue tracker on bitbucket. Sorry about that.

**Comment by blais** [comment]
This is a bug with parsing operator priorities, looks like a legit bug,
must be fixed.

**Comment by blais** [comment]
If I don't have a corresponding ticket on bb feel free to create one to
track status. This is high priority fix needed.

**Comment by blais** [comment]
https://bitbucket.org/blais/beancount/issues/27/sql-precedence-for-membership-in-operator

**Comment by blais** [comment]
Fixed:
https://bitbucket.org/blais/beancount/commits/c0fa32b74e94
