### ISSUE TITLE
bean-format failed when number contains comma

### ISSUE THREAD

**Issue by blais** [beancount/beancount#104]
**[Original report](https://bitbucket.org/blais/beancount/issue/104) by Yuchen Ying (Bitbucket: [yegle](https://bitbucket.org/yegle), GitHub: [yegle](https://github.com/yegle)).**

----------------------------------------

bean-check happily accept the file but bean-format doesn't agree:

```
$ cat test.bean
2016-03-09 open Assets:Test
2016-03-09 open Liabilities:Test
2016-03-09 *
    Assets:Test -20,000 USD
    Liabilities:Test 20,000 USD

$ bean-format test.bean
Traceback (most recent call last):
  File "/Users/yegle/.py3kvenv/bin/bean-format", line 2, in <module>
    from beancount.scripts.format import main; main()
  File "/Users/yegle/.py3kvenv/lib/python3.5/site-packages/beancount/scripts/format.py", line 153, in main
    formatted_contents = align_beancount(contents)
  File "/Users/yegle/.py3kvenv/lib/python3.5/site-packages/beancount/scripts/format.py", line 81, in align_beancount
    assert (old_stripped == new_stripped), (old_stripped, new_stripped)
AssertionError: ('2016-03-09 open Assets:Test 2016-03-09 open Liabilities:Test 2016-03-09 * Assets:Test -20,000 USD Liabilities:Test 20,000 USD', '2016-03-09 open Assets:Test 2016-03-09 open Liabilities:Test 2016-03-09 * Assets:Test Liabilities:Test')
```

**Comment by blais** [comment]
**Original comment by Zhen Cheng (Bitbucket: [wogong](https://bitbucket.org/wogong), GitHub: [wogong](https://github.com/wogong)).**

----------------------------------------

I found that it is OK if numbers contain a comma works in balance assertions, but failed in transactions. Wish this may be helpful.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

https://bitbucket.org/blais/beancount/commits/f0ab3bbd7e04f651a7072b231eebe0d30fc47af8
