### ISSUE TITLE
Too many transactions lead to closed-connection/connection-reset?

### ISSUE THREAD

**Issue by blais** [beancount/beancount#149]
**[Original report](https://bitbucket.org/blais/beancount/issue/149) by Unnamed (Bitbucket: [not_a_serious_name](https://bitbucket.org/not_a_serious_name)).**

----------------------------------------

**Environment**
Windows 10 Linux Subsystem, Python 3.5, Beancount 2.0b13

**Test Case**
Using attached examples files. 

```
#!bash

bean-web example.beancount
```

Account Liabilities:US:Chase:Slate has 500+ transactions and creates 1M+ response. Click this account will often get a connection_reset. 

![connection_reset.png](https://bitbucket.org/repo/7M55BB/images/673192920-connection_reset.png)

![connection_closed.png](https://bitbucket.org/repo/7M55BB/images/1164031290-connection_closed.png)

Earlier versions was OK.

**Comment by blais** [comment]
**Original comment by Dominik Aumayr (GitHub: [aumayr](https://github.com/aumayr)).**

----------------------------------------

Seems to be an issue with `bean-web` and not beancount itself, as [Fava](https://github.com/beancount/fava) (which itself uses/depends on beancount) loads the attached example-file just fine.

**Comment by blais** [comment]
**Original comment by Unnamed (Bitbucket: [not_a_serious_name](https://bitbucket.org/not_a_serious_name)).**

----------------------------------------

my fava got a connection-reset too...

![fava_reset.png](https://bitbucket.org/repo/7M55BB/images/2388431124-fava_reset.png)

**Comment by blais** [comment]
**Original comment by Dominik Aumayr (GitHub: [aumayr](https://github.com/aumayr)).**

----------------------------------------

Then it definitely looks like this is beancount + Windows-specific. I tested your example file on a Mac, where it loads just fine.
Maybe these are some hints for @blais ...

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

This is probably related to the fact bean-web is using the reference wsgi implementation, which is crappy. I'm using that because it requires no extra dependencies, but it sometimes causes failed requests, though I haven't seen a problem like this yet.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

I can't reproduce this on Linux. I don't have a Windows box. 
No idea.

**Comment by blais** [comment]
**Original comment by Unnamed (Bitbucket: [not_a_serious_name](https://bitbucket.org/not_a_serious_name)).**

----------------------------------------

correct: the current version is 2.0b13

**Comment by blais** [comment]
**Original comment by Unnamed (Bitbucket: [not_a_serious_name](https://bitbucket.org/not_a_serious_name)).**

----------------------------------------

Earlier versions of beancount was OK (2.0b6? Before Oct 2016).  What changed between these versions?

Is gcc version related? The only difficulty in installing beancount is to get a command 'x86_64-linux-gnu-gcc' failed with exit status 1 when install lxml, because gcc is not installed on default. My current Windows 10 Linux Subsystem is Ubuntu 14.04 with gcc 4.84. I tested in a virtual machine with Ubuntu 16.04 and gcc 5.4.0 and these is no problem. 

@blais You can get a free Win10 virtual machine from [Microsoft developer's site](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/), if you are interested. https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

**Comment by blais** [comment]
**Original comment by Unnamed (Bitbucket: [not_a_serious_name](https://bitbucket.org/not_a_serious_name)).**

----------------------------------------

I freshly re-installed my windows and still get this problem, both bean-web and fava. 

When it freezes, I press Ctrl-C and it returns:


```
#!cmd

127.0.0.1 - - [03/Jan/2017 16:34:18] "GET /view/all/journal/Liabilities:Credit HTTP/1.1" 200 1058571
127.0.0.1 - - [03/Jan/2017 16:34:19] "GET /view/all/journal/Liabilities:Credit HTTP/1.1" 200 1058571
^C----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53747)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/wsgiref/simple_server.py", line 119, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
----------------------------------------
```
bean-web:
![bean-web.png](https://bitbucket.org/repo/7M55BB/images/3212495046-bean-web.png)
fava:
![fava.png](https://bitbucket.org/repo/7M55BB/images/4111113059-fava.png)

**Comment by blais** [comment]
**Original comment by Unnamed (Bitbucket: [not_a_serious_name](https://bitbucket.org/not_a_serious_name)).**

----------------------------------------

problem gone after updating my windows to 15048…
