### ISSUE TITLE
issue with bean-web since python update to 3.6

### ISSUE THREAD

**Issue by blais** [beancount/beancount#153]
**[Original report](https://bitbucket.org/blais/beancount/issue/153) by jb M (Bitbucket: [jbbb](https://bitbucket.org/jbbb), GitHub: [jbbb](https://github.com/jbbb)).**

----------------------------------------

Since updating to python 3.6 (Arch Linux), I get a problem when using bean-web.

It fails and returns:

```

Bottle v0.12.12 server starting up (using WSGIRefServer())...
Listening on http://localhost:8080/
Hit Ctrl-C to quit.

Traceback (most recent call last):
  File "/usr/bin/bean-web", line 2, in <module>
    from beancount.web.web import main; main()
  File "/usr/lib/python3.6/site-packages/beancount/web/web.py", line 1190, in main
    run_app(args)
  File "/usr/lib/python3.6/site-packages/beancount/web/web.py", line 1108, in run_app
    quiet=args.quiet if hasattr(args, 'quiet') else quiet)
  File "/usr/bin/bottle.py", line 755, in run
    run(self, **kwargs)
  File "/usr/bin/bottle.py", line 3127, in run
    server.run(app)
  File "/usr/bin/bottle.py", line 2781, in run
    srv = make_server(self.host, self.port, app, server_cls, handler_cls)
  File "/usr/lib/python3.6/site-packages/beancount/web/web.py", line 1131, in stealing_make_server
    server = make_server(*args, **kw)
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 153, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)

```

Any ideas ?

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Thanks for reporting. I haven't installed 3.6 yet, I should do that and run the tests.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

I'm not able to reproduce this error. I installed 3.6 with its dependencies through pip on Ubuntu 16.04 and it works fine (apart from lots of BrokenPipe errors, but those are harmless, they're from the bad wsgiref implementation).

Can you provide more details?
Which page/resource are you accessing that brings about this error?
This looks like an error in bind()... are you sure you don't have another server using port 8080 on your machine?

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

I'll close for now, please reopen if this is not from an already occupied port or if you can provide steps to reproduce.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Can't repro. Probably an already used port.

**Comment by blais** [comment]
**Original comment by jb M (Bitbucket: [jbbb](https://bitbucket.org/jbbb), GitHub: [jbbb](https://github.com/jbbb)).**

----------------------------------------

Thank you for your answer. 


```
netstat -a | grep 8080

```

returns nothing which should indicate that the port is not being used before running bean-web. 

I'm using Archlinux and I installed beancount with the AUR verison. (I also tested the pip version and I am experiencing the same problem).

Strangely, it worked yesterday for some time, but it started bugging again. (rebooting doesn't fix it).

**Comment by blais** [comment]
**Original comment by jb M (Bitbucket: [jbbb](https://bitbucket.org/jbbb), GitHub: [jbbb](https://github.com/jbbb)).**

----------------------------------------

The issue was solved when upgrading python bottle. 

(updating to python-bottle-0.12.13-1 fixed it for me).
