### ISSUE TITLE
Traceback from bean-doctor checkdeps with filemagic

### ISSUE THREAD

**Issue by blais** [beancount/beancount#177]
**[Original report](https://bitbucket.org/blais/beancount/issue/177) by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

It seems the "python3-magic" package in Debian corresponds to filemagic rather than python-magic.  filemagic lacks from_file.  beancount/utils/file_type.py already checks for this but bean-doctor checkdeps gives a traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/bean-doctor", line 4, in <module>
    from beancount.scripts.doctor import main; main()
  File "/usr/local/lib/python3.5/dist-packages/beancount/scripts/doctor.py", line 392, in main
    function(opts.filename, opts.rest)
  File "/usr/local/lib/python3.5/dist-packages/beancount/scripts/doctor.py", line 184, in do_deps
    deps.list_dependencies(sys.stdout)
  File "/usr/local/lib/python3.5/dist-packages/beancount/scripts/deps.py", line 20, in list_dependencies
    for package, version, sufficient in check_dependencies():
TypeError: 'NoneType' object is not iterable
```

I've attached a proposed fix.

**Comment by blais** [comment]
**Original comment by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

Created pull request #27

**Comment by blais** [comment]
**Original comment by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

This got fixed in 4cf9581

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Thanks Martin.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

fixed in 4cf9581

**Comment by blais** [comment]
**Original comment by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

Just to add for future reference, python3-magic as of Debian buster (the current testing, what will become stable at some point) is the correct python-magic you expect.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Right. At some point the version checks will have to take into account the python-* vs. python3-* differences.
