### ISSUE TITLE
bean-report accounts traceback when no account opened

### ISSUE THREAD

**Issue by blais** [beancount/beancount#178]
**[Original report](https://bitbucket.org/blais/beancount/issue/178) by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

With the example file in which no accounts have been opened, I get a traceback with `bean-report accounts`:

```
2014-07-12 * "Black Iron Burger" ""
     Expenses:Food:Restaurant               17.23 USD
     Assets:Cash                           -17.23 USD
```

Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/bean-report", line 4, in <module>
    from beancount.reports.report import main; main()
  File "/usr/local/lib/python3.5/dist-packages/beancount/reports/report.py", line 251, in main
    chosen_report.render(entries, errors, options_map, args.format, outfile)
  File "/usr/local/lib/python3.5/dist-packages/beancount/reports/base.py", line 114, in render
    result = render_method(entries, errors, options_map, outfile)
  File "/usr/local/lib/python3.5/dist-packages/beancount/reports/misc_reports.py", line 94, in render_beancount
    maxlen = max(len(account) for account in open_close)
ValueError: max() arg is an empty sequence
```

I've attached a fix.

**Comment by blais** [comment]
**Original comment by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

Created pull request beancount/beanquery#64

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Accepted related pull request. Thank you Martin!
