### ISSUE TITLE
beancount error in Arch

### ISSUE THREAD

**Issue by blais** [beancount/beancount#189]
**[Original report](https://bitbucket.org/blais/beancount/issue/189) by Jib (Bitbucket: [jibzzz](https://bitbucket.org/jibzzz), GitHub: [jibzzz](https://github.com/jibzzz)).**

----------------------------------------

When I run a beancount command (or fava) I get an error: for example`$ bean-check Documents/beancount.beancount ` returns

```
Traceback (most recent call last):
  File "/usr/bin/bean-check", line 2, in <module>
    from beancount.scripts.check import main; main()
  File "/usr/lib/python3.6/site-packages/beancount/scripts/check.py", line 39, in main
    extra_validations=validation.HARDCORE_VALIDATIONS)
  File "/usr/lib/python3.6/site-packages/beancount/loader.py", line 87, in load_file
    extra_validations, encoding)
  File "/usr/lib/python3.6/site-packages/beancount/loader.py", line 200, in wrapped
    result = function(toplevel_filename, *args, **kw)
  File "/usr/lib/python3.6/site-packages/beancount/loader.py", line 219, in _load_file
    return _load([(filename, True)], *args, **kw)
  File "/usr/lib/python3.6/site-packages/beancount/loader.py", line 460, in _load
    extra_validations)
  File "/usr/lib/python3.6/site-packages/beancount/ops/validation.py", line 395, in validate
    new_errors = validation_function(entries, options_map)
  File "/usr/lib/python3.6/site-packages/beancount/ops/validation.py", line 348, in validate_check_transaction_balances
    "Transaction does not balance: {}".format(residual),
  File "/usr/lib/python3.6/site-packages/beancount/core/inventory.py", line 106, in __str__
    return self.to_string()
  File "/usr/lib/python3.6/site-packages/beancount/core/inventory.py", line 98, in to_string
    ', '.join(pos.to_string(dformat) for pos in sorted(self)))
  File "/usr/lib/python3.6/site-packages/beancount/core/position.py", line 228, in __lt__
    return self.sortkey() < other.sortkey()
  File "/usr/lib/python3.6/site-packages/beancount/core/position.py", line 210, in sortkey
    order_units = CURRENCY_ORDER.get(currency, NCURRENCIES + len(currency))
TypeError: object of type 'type' has no len()
```

This is a new error, I started experiencing it today.

I use Arch, and got beancount from [this AUR package](https://aur.archlinux.org/packages/beancount/).

Any ideas ?

**Comment by blais** [comment]
**Original comment by Jib (Bitbucket: [jibzzz](https://bitbucket.org/jibzzz), GitHub: [jibzzz](https://github.com/jibzzz)).**

----------------------------------------

was caused by error in beancount file

(conversion rate between currencies)

**Comment by blais** [comment]
**Original comment by ngoonee NA (Bitbucket: [ngoonee](https://bitbucket.org/ngoonee), GitHub: [ngoonee](https://github.com/ngoonee)).**

----------------------------------------

In future the best (IMHO) place to report this would be in the AUR package's comments, in case it's a packaging issue (in which case others would corroborate there) or configuration/personal issue (in which case others would also confirm it works for them).

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Jib: Can you share the file which caused the exception to occur? If not, can you chop it down to minimum file that would reproduce the problem?

Exceptions are always errors. I can fix it, I just need to be able to reproduce it.

Thanks,
