### ISSUE TITLE
In the web interface, clicking on a directive that has no context generates an error

### ISSUE THREAD

**Issue by blais** [beancount/beancount#19]
**[Original report](https://bitbucket.org/blais/beancount/issue/19) by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

  - BUG: In web interface... clicking on a directive that cannot be contexted
    right generates an error like this:

      127.0.0.1 - - [25/Jan/2015 00:41:33] "GET
      /context/7a79f22d284d032e2b28501e904e4826 HTTP/1.1" 500 59
      Traceback (most recent call last):
        File "/usr/local/lib/python3.4/wsgiref/handlers.py", line 137, in run
          self.result = application(self.environ, self.start_response)
        File "/usr/local/lib/python3.4/site-packages/bottle.py", line 979, in __call__
          return self.wsgi(environ, start_response)
        File "/usr/local/lib/python3.4/site-packages/bottle.py", line 954, in wsgi
          out = self._cast(self._handle(environ))
        File "/usr/local/lib/python3.4/site-packages/bottle.py", line 862, in _handle
          return route.call(**args)
        File "/usr/local/lib/python3.4/site-packages/bottle.py", line 1729, in wrapper
          rv = callback(*a, **ka)
        File "/home/blais/p/beancount/src/python/beancount/web/web.py", line 939, in
        wrapper
          return callback(*posargs, **kwargs)
        File "/home/blais/p/beancount/src/python/beancount/web/web.py", line 381, in
        context_
          app.entries, dcontext, entry.meta.filename, entry.meta.lineno))
        File "/home/blais/p/beancount/src/python/beancount/reports/context.py", line
        33, in render_entry_context
          raise SystemExit("No entry could be found before {}:{}".format(filename,
          lineno))

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------


```
#!python

      127.0.0.1 - - [25/Jan/2015 00:41:33] "GET
      /context/7a79f22d284d032e2b28501e904e4826 HTTP/1.1" 500 59
      Traceback (most recent call last):
        File "/usr/local/lib/python3.4/wsgiref/handlers.py", line 137, in run
          self.result = application(self.environ, self.start_response)
        File "/usr/local/lib/python3.4/site-packages/bottle.py", line 979, in __call__
          return self.wsgi(environ, start_response)
        File "/usr/local/lib/python3.4/site-packages/bottle.py", line 954, in wsgi
          out = self._cast(self._handle(environ))
        File "/usr/local/lib/python3.4/site-packages/bottle.py", line 862, in _handle
          return route.call(**args)
        File "/usr/local/lib/python3.4/site-packages/bottle.py", line 1729, in wrapper
          rv = callback(*a, **ka)
        File "/home/blais/p/beancount/src/python/beancount/web/web.py", line 939, in
        wrapper
          return callback(*posargs, **kwargs)
        File "/home/blais/p/beancount/src/python/beancount/web/web.py", line 381, in
        context_
          app.entries, dcontext, entry.meta.filename, entry.meta.lineno))
        File "/home/blais/p/beancount/src/python/beancount/reports/context.py", line
        33, in render_entry_context
          raise SystemExit("No entry could be found before {}:{}".format(filename,
          lineno))

```
