### ISSUE TITLE
Cost currency same as unit currency will fail with an assertion, not a reported error

### ISSUE THREAD

**Issue by blais** [beancount/beancount#22]
**[Original report](https://bitbucket.org/blais/beancount/issue/22) by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

  - BUG: This will fail with an assertion, should be an error instead:

       2014-11-01 * "Massdrop Group Inc." | "Express Checkout Payment Sent"
         Expenses:Toys:Electronics    146.37 USD @@ 169.87 USD
         Assets:CA:PayPal      -169.87 CAD

```
#!python

bean-check /tmp/test.beancount
Traceback (most recent call last):
  File "/home/blais/p/beancount1/src/python/beancount/parser/parser.py", line 776, in transaction
    balance_errors = balance_incomplete_postings(entry)
  File "/home/blais/p/beancount1/src/python/beancount/core/interpolate.py", line 238, in balance_incomplete_postings
    postings, inserted, errors = get_incomplete_postings(entry)
  File "/home/blais/p/beancount1/src/python/beancount/core/interpolate.py", line 151, in get_incomplete_postings
    balance_amount = get_posting_weight(posting)
  File "/home/blais/p/beancount1/src/python/beancount/core/interpolate.py", line 49, in get_posting_weight
    return posting.position.get_weight(posting.price)
  File "/home/blais/p/beancount1/src/python/beancount/core/position.py", line 239, in get_weight
    "Invalid currency for price: {} in {}".format(self, price))
AssertionError: Invalid currency for price: 146.37 USD in 1.160552025688324110131857621 USD


```

**Comment by blais** [comment]
**Original comment by Justus Pendleton (Bitbucket: [hoostus](https://bitbucket.org/hoostus), GitHub: [hoostus](https://github.com/hoostus)).**

----------------------------------------

This no longer fails with an assertion.

Instead you'll get an error message that looks like:


```
#!

/Users/justus/beancount/examples/example.beancount:7179:    Transaction does not balance: (169.8700000000000000000000000 USD, -169.87 CAD)

   2018-08-07 * "Massdrop Group Inc." "Express Checkout Payment Sent"
     Expenses:Food:Coffee   146.37 USD @ 1.160552025688324110131857621 USD
     Assets:CA:PayPal      -169.87 CAD

```

On the one hand, the bug-as-reported is no longer valid so maybe this issue should be closed? On the other hand, I'm not sure that "transaction does not balance" is the most helpful error message when the real problem is wrong use of the cost currency. The error message isn't *wrong*, though. I'm a bit on the fence about whether this is good enough as-is and should just be closed.

Thoughts @blais ?
