### ISSUE TITLE
bql: CURRENCY_META and getitem() undocumented

### ISSUE THREAD

**Issue by blais** [beancount/beancount#260]
**[Original report](https://bitbucket.org/blais/beancount/issue/260) by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

I don't know if this is a documentation issue or a bug but I cannot figure out how to use CURRENCY_META().

"help from" says it returns a dict. How do I query a dict in BLQ?

```
beancount> SELECT COMMODITY_META("GBP");
Traceback (most recent call last):
  File "/usr/lib/python3.5/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'BQLShell' object has no attribute 'do_SELECT'
...
  File "/home/tbm/.local/lib/python3.5/site-packages/beancount/query/query_render.py", line 452, in get_renderers
    for _, dtype in result_types]
  File "/home/tbm/.local/lib/python3.5/site-packages/beancount/query/query_render.py", line 452, in <listcomp>
    for _, dtype in result_types]
KeyError: <class 'dict'>
```

with

```
1970-01-01 commodity GBP
  assets: "cash"

2018-02-17 * "Iceland" "Supermarket"
  Expenses:Supermarket                                      2.00 GBP
  Liabilities:Credit-Card                                  -2.00 GBP
```

**Comment by blais** [comment]
**Original comment by Patrick Ruckstuhl (GitHub: [tarioch](https://github.com/tarioch)).**

----------------------------------------

Use getitem(commodity_meta(currency), "assets")

**Comment by blais** [comment]
**Original comment by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

Thank you!

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

The new query engine will sport proper documentation (but separately from Beancount, it'll likely be a new project.)
