### ISSUE TITLE
KeyError: 'USD' running returns.py due to date calculation

### ISSUE THREAD

**Issue by blais** [beancount/beancount#29]
**[Original report](https://bitbucket.org/blais/beancount/issue/29) by Aaron Bull Schaefer (Bitbucket: [elasticdog](https://bitbucket.org/elasticdog), GitHub: [elasticdog](https://github.com/elasticdog)).**

----------------------------------------

Due to the dates listed for some of my accounts, the *returns.py* script tried to generate returns for periods where there were no transactions. This caused the error when trying to print:

```
Returns for Aaron's Fidelity 401k account
  Period            Begin      -> End       :        Total   Annualized
Traceback (most recent call last):
  File "./returns.py", line 90, in <module>
    main()
  File "./returns.py", line 86, in main
    total_returns['USD'] - 1, annual_returns['USD'] - 1))
KeyError: 'USD'
```

...I'm not very familiar with Python dev, but to work around that locally I just added a test for the key before printing:

```python
if 'USD' in total_returns:
    print(FORMAT.format(period_name, str(date_begin), str(date_end),
                        total_returns['USD'] - 1, annual_returns['USD'] - 1))
```

I'm sure there's probably a cleaner solution, but I wanted to make you aware that I hit this issue.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Thanks for the bug report Aaron.
Do you think it would be possible to recreate the problem with a minimal input file?
That would save me some time.
In any case, thank you,

**Comment by blais** [comment]
**Original comment by Aaron Bull Schaefer (Bitbucket: [elasticdog](https://bitbucket.org/elasticdog), GitHub: [elasticdog](https://github.com/elasticdog)).**

----------------------------------------

Sure thing...let me see what I can come up with.

**Comment by blais** [comment]
This has been completely rewritten to a "beangrow" repo. Out of date.
