### ISSUE TITLE
bean-check fails on a transaction with no values

### ISSUE THREAD

**Issue by blais** [beancount/beancount#3]
**[Original report](https://bitbucket.org/blais/beancount/issue/3) by Matthew Harris (Bitbucket: [matthew_harris](https://bitbucket.org/matthew_harris), GitHub: [mharris312](https://github.com/mharris312)).**

----------------------------------------

Sample inputs:

2000-01-01 * "Test"
  Assets:Foo

2000-01-01 * "Test"
  Assets:Foo
  Assets:Bar

For either of these sample inputs, bean-check gives the following stack trace:

$ bean-check test.beancount 
Traceback (most recent call last):
  File "/Users/mharris/homebrew/bin/bean-check", line 2, in <module>
    from beancount.scripts.check import main; main()
  File "/Users/mharris/homebrew/lib/python3.4/site-packages/beancount/scripts/check.py", line 39, in main
    extra_validations=validation.HARDCORE_VALIDATIONS)
  File "/Users/mharris/homebrew/lib/python3.4/site-packages/beancount/loader.py", line 52, in load_file
    return _load(parser.parse_file, filename, log_timings, log_errors, extra_validations)
  File "/Users/mharris/homebrew/lib/python3.4/site-packages/beancount/loader.py", line 125, in _load
    printer.print_errors(errors, file=log_errors)
  File "/Users/mharris/homebrew/lib/python3.4/site-packages/beancount/parser/printer.py", line 324, in print_errors
    output.write(format_error(error))
  File "/Users/mharris/homebrew/lib/python3.4/site-packages/beancount/parser/printer.py", line 294, in format_error
    error_string = '\n'.join(format_entry(entry) for entry in entries)
  File "/Users/mharris/homebrew/lib/python3.4/site-packages/beancount/parser/printer.py", line 294, in <genexpr>
    error_string = '\n'.join(format_entry(entry) for entry in entries)
  File "/Users/mharris/homebrew/lib/python3.4/site-packages/beancount/parser/printer.py", line 224, in format_entry
    return EntryPrinter(dcontext, render_weights)(entry)
  File "/Users/mharris/homebrew/lib/python3.4/site-packages/beancount/parser/printer.py", line 105, in __call__
    method(obj, oss)
  File "/Users/mharris/homebrew/lib/python3.4/site-packages/beancount/parser/printer.py", line 131, in Transaction
    width_account = max(len(flag_account) for flag_account in strs_account)
ValueError: max() arg is an empty sequence

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Fixed #3: bug with printer that would fail on incomplete number of postings to print.
