### ISSUE TITLE
'Transaction' object has no attribute 'source' ← when requesting BQL field "filename"

### ISSUE THREAD

**Issue by blais** [beancount/beancount#30]
**[Original report](https://bitbucket.org/blais/beancount/issue/30) by clemente (Bitbucket: [clemente](https://bitbucket.org/clemente), GitHub: [clemente](https://github.com/clemente)).**

----------------------------------------

~~~~
: dc; /w/beancount ; /w/beancount ; PYTHONPATH=/w/beancount/src/python /w/beancount/bin/bean-query ~/my.beancount 
Input file: "Beancount"
Ready with 3 directives (2 postings in 1 transactions).
beancount> select account,filename;
Traceback (most recent call last):
  File "/usr/lib/python3.4/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'BQLShell' object has no attribute 'do_select'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/w/beancount/src/python/beancount/query/shell.py", line 225, in default
    self.dispatch(statement)
  File "/w/beancount/src/python/beancount/query/shell.py", line 215, in dispatch
    return method(statement)
  File "/w/beancount/src/python/beancount/query/shell.py", line 358, in on_Select
    self.options_map)
  File "/w/beancount/src/python/beancount/query/query_execute.py", line 215, in execute_query
    values = [c_expr(context) for c_expr in c_target_exprs]
  File "/w/beancount/src/python/beancount/query/query_execute.py", line 215, in <listcomp>
    values = [c_expr(context) for c_expr in c_target_exprs]
  File "/w/beancount/src/python/beancount/query/query_env.py", line 655, in __call__
    return context.posting.entry.source.filename
AttributeError: 'Transaction' object has no attribute 'source'
beancount> exit
~~~~

The file is just:

~~~~
1970-01-01 open Expenses:Something
1970-01-01 open Assets:Account

1999-02-13 * "test"
  Expenses:Something		52200 PTA
  Assets:Account -52200 PTA
~~~~

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Fixed #30, incomplete port of directive .source  attribute to .meta in  query environment. Also added a function to convert amount to market value  (not useful yet, I need to deal with inventories and positions).
