### ISSUE TITLE
Install via pip3 fails if hg not installed.

### ISSUE THREAD

**Issue by blais** [beancount/beancount#309]
**[Original report](https://bitbucket.org/blais/beancount/issue/309) by Joe Planisky (Bitbucket: [jplanisky](https://bitbucket.org/jplanisky), GitHub: [jplanisky](https://github.com/jplanisky)).**

----------------------------------------

Attempting to install via pip3 on Mac OS 10.12.6 fails with 
```
#!python

$ pip3 install beancount
Collecting beancount
  Using cached https://files.pythonhosted.org/packages/3c/c5/f8ab88323ebef96d8b17e36e70cee268fec298881169cd7559d1907a5ccf/beancount-2.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/cm/yp6lqtt55xd4r91b7ygtxfbr0000gn/T/pip-build-owvyj6ij/beancount/setup.py", line 197, in <module>
        changeset_timestamp = get_changeset()
      File "/private/var/folders/cm/yp6lqtt55xd4r91b7ygtxfbr0000gn/T/pip-build-owvyj6ij/beancount/setup.py", line 173, in get_hg_changeset
        shell=False)
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 403, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    PermissionError: [Errno 13] Permission denied: 'hg'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/cm/yp6lqtt55xd4r91b7ygtxfbr0000gn/T/pip-build-owvyj6ij/beancount/
```
I believe this is due to a [bug in Python3](https://bugs.python.org/issue25481) where `subprocess.check_output()` raises a `PermissionError` if the executable isn't found instead of the (expected) `FileNotFound` exception.  Although that bug report talks about an inaccessible directory on the path, it seems to apply to executables that don't exist.  

```
#!python

$ python3
Python 3.6.5 (default, May  1 2018, 19:59:44) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.check_output(['nosuchfile'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'nosuchfile'
```
The fix for beancount would be to add `PermissionError` to the list of expected exceptions in `get_hg_changeset` and `get_git_changeset` in `setup.py`.

**Comment by blais** [comment]
**Original comment by Rodrigo Camacho (Bitbucket: machocam NA, GitHub: [machocam](https://github.com/machocam)).**

----------------------------------------

I'm currently getting this error - was this ever fixed? 
What should I change in my system to get rid of this?

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

FIxed at https://bitbucket.org/blais/beancount/commits/ef3d130c6d898064c05d0d31a64abd3e064d6db8

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

This error seems unlikely. 
I have no idea why it's trying to interpret the first argument as a directory name.
I can't reproduce this. 
I'm afraid you're going to have to debug this further and send me a patch.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

(That'll circumvent the issue, but we will don't know why it fails in the first place.)

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

I tried to reproduce this on my mac, but couldn't.
Then I realized, I think the problem is that you're not seeing the change I had pushed because  you're pulling from the latest release. I haven't triggered a release with that change yet.

I would suggest already working from head and using "pipp3 install ." in the base directory instead. This way you can always update at your convenience. Beancount releases lag a fair bit and are for the very most conservative.
