### ISSUE TITLE
NameError: name 'prices' is not defined

### ISSUE THREAD

**Issue by blais** [beancount/beancount#31]
**[Original report](https://bitbucket.org/blais/beancount/issue/31) by clemente (Bitbucket: [clemente](https://bitbucket.org/clemente), GitHub: [clemente](https://github.com/clemente)).**

----------------------------------------

~~~~
beancount> select price,convert(price,'EUR')
Traceback (most recent call last):
  File "/usr/lib/python3.4/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'BQLShell' object has no attribute 'do_select'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/w/beancount/src/python/beancount/query/shell.py", line 225, in default
    self.dispatch(statement)
  File "/w/beancount/src/python/beancount/query/shell.py", line 215, in dispatch
    return method(statement)
  File "/w/beancount/src/python/beancount/query/shell.py", line 358, in on_Select
    self.options_map)
  File "/w/beancount/src/python/beancount/query/query_execute.py", line 220, in execute_query
    values = [c_expr(context) for c_expr in c_target_exprs]
  File "/w/beancount/src/python/beancount/query/query_execute.py", line 220, in <listcomp>
    values = [c_expr(context) for c_expr in c_target_exprs]
  File "/w/beancount/src/python/beancount/query/query_env.py", line 229, in __call__
    return prices.convert_amount(context.price_map, args[1], args[0])
NameError: name 'prices' is not defined
~~~~

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

There's an easy "fix" to this, but it won't help, the feature isn't quite ready.
It turns out correctly computing market prices requires a bit more thought.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

To resolve this issue, complete working out the semantics of the CONVERT() function in SQL. In particular, it should do something right if no price is available in the price database.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

I think this issue has been addressed at this point, with CONVERT() and GETPRICE() and such.
