### ISSUE TITLE
'ParserSyntaxError' object has no attribute 'meta'

### ISSUE THREAD

**Issue by blais** [beancount/beancount#4]
**[Original report](https://bitbucket.org/blais/beancount/issue/4) by Matthew Harris (Bitbucket: [matthew_harris](https://bitbucket.org/matthew_harris), GitHub: [mharris312](https://github.com/mharris312)).**

----------------------------------------

If I run bean-web on a trivial erroneous input file (e.g. a file containing just the text "hello world") and visit the errors page (http://localhost:8080/errors), I get the following error on the console:

Bottle v0.12.7 server starting up (using WSGIRefServer())...
Listening on http://localhost:8080/
Hit Ctrl-C to quit.

INFO    : Reloading...
,----------------------------------------------------------------
test.beancount:1:       syntax error, unexpected ERROR

test.beancount:1:       Lexer error; erroneous token: 'hello'

test.beancount:1:       Lexer error; erroneous token: 'world'

`----------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mharris/homebrew/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Users/mharris/homebrew/bin/bottle.py", line 1729, in wrapper
    rv = callback(*a, **ka)
  File "/Users/mharris/homebrew/lib/python3.4/site-packages/beancount/web/web.py", line 939, in wrapper
    return callback(*posargs, **kwargs)
  File "/Users/mharris/homebrew/lib/python3.4/site-packages/beancount/web/web.py", line 317, in errors
    contents=render_report(misc_reports.ErrorReport, [], leaf_only=False))
  File "/Users/mharris/homebrew/lib/python3.4/site-packages/beancount/web/web.py", line 154, in render_report
    report_.render_htmldiv(entries, app.errors, app.options, oss)
  File "/Users/mharris/homebrew/lib/python3.4/site-packages/beancount/reports/misc_reports.py", line 50, in render_htmldiv
    printer.render_source(error.meta)))
AttributeError: 'ParserSyntaxError' object has no attribute 'meta'
127.0.0.1 - - [03/Jan/2015 01:27:03] "GET /errors HTTP/1.1" 500 747

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Fixed bug #4: error in rendering errors in misc_reports; also fixed various typos.
