### ISSUE TITLE
bean-example fails - unit test succeeds, running the script fails

### ISSUE THREAD

**Issue by blais** [beancount/beancount#41]
**[Original report](https://bitbucket.org/blais/beancount/issue/41) by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

nosetests3 /home/blais/p/beancount/src/python/beancount/scripts/example_test.py
flex scanner push-back overflow

While running bean-example I get this error:

```
INFO    : Writing contents
Traceback (most recent call last):
  File "/usr/bin/bean-example", line 2, in <module>
    from beancount.scripts.example import main; main()
  File "/usr/lib/python3.4/site-packages/beancount/scripts/example.py", line 1743, in main
    file=output_file)
  File "/usr/lib/python3.4/site-packages/beancount/scripts/example.py", line 1693, in write_example_file
    file.write(contents)
UnicodeEncodeError: 'ascii' codec can't encode character '\xae' in position 1192: ordinal not in range(128)
```

-- 
Evan Farrell
Full Stack Engineer
Professional Taster
Analytical Flavor Systems, LLC.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

This fixes the generation bug: 
https://bitbucket.org/blais/beancount/commits/8b4372ec9599cf2c2faf78eb808e5d48897f999d

However, it's still quite concerning that the flex scanner fails on the unit test. 
I still need to look into this.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

(closing old tickets - and AFAIK this has been resolved)
