### ISSUE TITLE
Decimal-None in unrealized gains with cost 0

### ISSUE THREAD

**Issue by blais** [beancount/beancount#43]
**[Original report](https://bitbucket.org/blais/beancount/issue/43) by clemente (Bitbucket: [clemente](https://bitbucket.org/clemente), GitHub: [clemente](https://github.com/clemente)).**

----------------------------------------

~~~~
plugin "beancount.plugins.unrealized"

2001-01-01 open Assets:BAC
2001-01-01 open Assets:Cash
2001-01-01 open Income:BAC
2001-01-01 open Equity:NotYetAccounted


2013-05-20 pad Assets:BAC Equity:NotYetAccounted
2013-05-20 balance Assets:BAC 14 BAC

2013-06-30 ! "My 14 gifted shares are sold"
  Assets:BAC -14 BAC {0 EUR} @@ 7.64 EUR
  Assets:Cash 7.64 EUR
  Income:BAC
~~~~

I get:
~~~~
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python3/dist-packages/bottle.py", line 1729, in wrapper
    rv = callback(*a, **ka)
  File "/w/beancount/src/python/beancount/web/web.py", line 912, in wrapper
    entries, errors, options_map = loader.load_file(filename)
  File "/w/beancount/src/python/beancount/loader.py", line 57, in load_file
    return _load([(filename, True)], log_timings, log_errors, extra_validations)
  File "/w/beancount/src/python/beancount/loader.py", line 221, in _load
    entries, errors = run_transformations(entries, parse_errors, options_map, log_timings)
  File "/w/beancount/src/python/beancount/loader.py", line 292, in run_transformations
    entries, plugin_errors = callback(entries, options_map)
  File "/w/beancount/src/python/beancount/plugins/unrealized.py", line 105, in add_unrealized_gains
    pnl = holding.market_value - holding.book_value
TypeError: unsupported operand type(s) for -: 'decimal.Decimal' and 'NoneType'
~~~~

The test case above is simplified (in real life I should have *received* those 0 EUR first), but my original transactions where this happes crash in the same way.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Fixed issue #43 - a bug that only triggers when cost values are zero.
