### ISSUE TITLE
crash with use_legacy_fixed_tolerances True

### ISSUE THREAD

**Issue by blais** [beancount/beancount#47]
**[Original report](https://bitbucket.org/blais/beancount/issue/47) by clemente (Bitbucket: [clemente](https://bitbucket.org/clemente), GitHub: [clemente](https://github.com/clemente)).**

----------------------------------------

When using 
~~~~
option "use_legacy_fixed_tolerances" "TRUE"
~~~~
I get:
~~~~
Traceback (most recent call last):
  File "/w/beancount/src/python/beancount/parser/parser.py", line 806, in transaction
    balance_errors = balance_incomplete_postings(entry, self.options)
  File "/w/beancount/src/python/beancount/core/interpolate.py", line 364, in balance_incomplete_postings
    residual, tolerances) = get_incomplete_postings(entry, options_map)
  File "/w/beancount/src/python/beancount/core/interpolate.py", line 314, in get_incomplete_postings
    quantum = (tolerance * 2).normalize()
AttributeError: 'str' object has no attribute 'normalize'
~~~~

If you need I create a test case.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

What were the values you used for the tolerance options in your input file?

**Comment by blais** [comment]
**Original comment by clemente (Bitbucket: [clemente](https://bitbucket.org/clemente), GitHub: [clemente](https://github.com/clemente)).**

----------------------------------------

I used many per-currency tolerances around 0.005, but the crash happens even if don't specify any tolerance. This is a minimal valid file which crashes:

~~~~
option "use_legacy_fixed_tolerances" "TRUE"

1970-01-01 open Assets:B1
1970-01-01 open Assets:B2

2010-01-01 * "something"
  Assets:B1		 -200 EUR
  Assets:B2
~~~~

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Fixed issue 47 - use_legacy_fixed_tolerances default value wasn't initialized properly to a decimal object.

I also added a test.
