### ISSUE TITLE
Exception in leafonly plugin if non-leaf account has no Open directive

### ISSUE THREAD

**Issue by blais** [beancount/beancount#5]
**[Original report](https://bitbucket.org/blais/beancount/issue/5) by Nathan  Grigg (Bitbucket: [nathangrigg](https://bitbucket.org/nathangrigg), GitHub: [nathangrigg](https://github.com/nathangrigg)).**

----------------------------------------

If you have a non-leaf posting on an account that doesn't exist, the leafonly plugin raises an AttributeError if there is no Open directive. The problem is that 'open_entry' is None.

https://bitbucket.org/blais/beancount/src/317b0a91b8d584380b0b750ae438f8af334ef911/src/python/beancount/plugins/leafonly.py?at=default#cl-41

```
#!python

Traceback (most recent call last):
  File "/usr/local/python3/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/python3/bin/bottle.py", line 1729, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/python3/lib/python3.4/site-packages/beancount/web/web.py", line 912, in wrapper
    entries, errors, options_map = loader.load_file(filename)
  File "/usr/local/python3/lib/python3.4/site-packages/beancount/loader.py", line 52, in load_file
    return _load(parser.parse_file, filename, log_timings, log_errors, extra_validations)
  File "/usr/local/python3/lib/python3.4/site-packages/beancount/loader.py", line 111, in _load
    entries, errors = run_transformations(entries, parse_errors, options_map, log_timings)
  File "/usr/local/python3/lib/python3.4/site-packages/beancount/loader.py", line 182, in run_transformations
    entries, plugin_errors = callback(entries, options_map)
  File "/usr/local/python3/lib/python3.4/site-packages/beancount/plugins/leafonly.py", line 43, in validate_leaf_only
    open_entry.meta,
AttributeError: 'NoneType' object has no attribute 'meta'
```

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Fixed issue #5: Error when posting on non-leaf account without an Open directive.
