### ISSUE TITLE
Bazel does not compile on Mac OS

### ISSUE THREAD

**Issue by jbeder** [beancount/beancount#573]
Steps to reproduce:

1. Environment:
  - OS 10.15.7
  - python version 3.8.5
  - beancount 2.3.3
2. Run `bazel build //bin:all`

Full output:

```
INFO: Analyzed 30 targets (38 packages loaded, 550 targets configured).
INFO: Found 30 targets...
INFO: From Linking beancount/parser/libdecimal_c.a:
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: bazel-out/darwin-opt/bin/beancount/parser/libdecimal_c.a the table of contents is empty (no object file members in the library define global symbols)
INFO: From Compiling beancount/parser/lexer.c:
beancount/parser/lexer.c:2212:16: warning: function 'input' is not needed and will not be emitted [-Wunneeded-internal-declaration]
    static int input  (yyscan_t yyscanner)
               ^
1 warning generated.
ERROR: /Users/beder/Downloads/beancount-2.3.3/beancount/parser/BUILD:359:13: Linking of rule '//beancount/parser:_parser.so' failed (Exit 1) cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -lc++ -fobjc-link-runtime -shared -o bazel-out/darwin-opt/bin/beancount/parser/_parser.so ... (remaining 11 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
ld: unknown option: --export-dynamic-symbol=PyInit__parser
clang: error: linker command failed with exit code 1 (use -v to see invocation)
INFO: Elapsed time: 4.274s, Critical Path: 1.51s
INFO: 28 processes: 28 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

I believe the `--export-dynamic-symbol` flag comes from `third_party/python/py_extension.bzl`, and there's a comment there:

> Ensure that the init function is exported. Required for gold.

I'm not sure what this means, but if I remove the flag, the build compiles and links, but then fails with missing symbols if I run any binary, e.g.:

```
$ bazel run //bin:bean_check
INFO: Analyzed target //bin:bean_check (1 packages loaded, 67 targets configured).
INFO: Found 1 target...
Target //bin:bean_check up-to-date:
  bazel-bin/bin/bean_check.py
  bazel-bin/bin/bean_check
INFO: Elapsed time: 0.262s, Critical Path: 0.10s
INFO: 1 process: 1 darwin-sandbox.
INFO: Build completed successfully, 2 total actions
INFO: Build completed successfully, 2 total actions
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_beder/cb97eb509905f10b4b346a1d0556de4a/execroot/beancount/bazel-out/darwin-opt/bin/bin/bean_check.runfiles/beancount/bin/bean_check.py", line 5, in <module>
    from beancount.scripts.check import main
  File "/private/var/tmp/_bazel_beder/cb97eb509905f10b4b346a1d0556de4a/execroot/beancount/bazel-out/darwin-opt/bin/bin/bean_check.runfiles/beancount/beancount/scripts/check.py", line 11, in <module>
    from beancount import loader
  File "/private/var/tmp/_bazel_beder/cb97eb509905f10b4b346a1d0556de4a/execroot/beancount/bazel-out/darwin-opt/bin/bin/bean_check.runfiles/beancount/beancount/loader.py", line 25, in <module>
    from beancount.parser import parser
  File "/private/var/tmp/_bazel_beder/cb97eb509905f10b4b346a1d0556de4a/execroot/beancount/bazel-out/darwin-opt/bin/bin/bean_check.runfiles/beancount/beancount/parser/parser.py", line 118, in <module>
    from beancount.parser import _parser
ImportError: dlopen(/private/var/tmp/_bazel_beder/cb97eb509905f10b4b346a1d0556de4a/execroot/beancount/bazel-out/darwin-opt/bin/bin/bean_check.runfiles/beancount/beancount/parser/_parser.so, 2): Symbol not found: _decimal_type
  Referenced from: /private/var/tmp/_bazel_beder/cb97eb509905f10b4b346a1d0556de4a/execroot/beancount/bazel-out/darwin-opt/bin/bin/bean_check.runfiles/beancount/beancount/parser/_parser.so
  Expected in: flat namespace
 in /private/var/tmp/_bazel_beder/cb97eb509905f10b4b346a1d0556de4a/execroot/beancount/bazel-out/darwin-opt/bin/bin/bean_check.runfiles/beancount/beancount/parser/_parser.so
```

**Comment by jbeder** [comment]
PR #574 fixes this issue along with removing the `linkopts` from `py_extension.bzl`. Obviously (I assume) you want to keep that for Linux builds, so I'm looking into this. (I think Bazel allows different options for different platforms, but I'm not sure.)

**Comment by dnicolodi** [comment]
I would just remove the Bazel build from v2. It does not buy us anything there and I don't think we have the bandwidth to maintain it. The fact that we have not been able to fix it to run in the CI is telling. @jbeder, what is your interest in building v2 with Bazel?

**Comment by jbeder** [comment]
I’d like to use beancount with a project that already used Bazel, so if I
can’t use the existing Bazel build, I’ll probably try to wrap the setup.py
a Bazel rule or something. Unless I’m misreading the whole v2/v3 thing, is
v3 available yet?

Also, it does seem to (mostly) work - on my run, all but two of the tests
pass. I didn’t dig into the failing ones, but that indicates to me that the
essential part of the configuration is correct.

**Comment by blais** [comment]
> I would just remove the Bazel build from v2. It does not buy us anything there and I don't think we have the bandwidth to maintain it. The fact that we have not been able to fix it to run in the CI is telling. @jbeder, what is your interest in building v2 with Bazel?

v2 Bazel build is necessary until v3 is ready for action. There is a crossover point when the v3 C++ parser is able to produce its data like the v2 one and interplay with the rest of the system in Python (all tests passing), so that v3 is usable with the new parser. ETA Xmas~NYE, maybe, if there is time to play. It's looking promising.

Before the crossover point: handling bug fixes in v2 that involves changing any important without a Bazel build would require immediately fixing up the build rules in v3/master, so until the crosssover point, Bazel build in v2 helps avoid this problem and I want to maintain it.

After the crossover point, the standard answer for bug fixes will be "no time,l move to v3." At that point we could remove the Bazel build in v2, there won't be a point anymore (not a whole lot of action will be seen there).

**Comment by blais** [comment]
> I’d like to use beancount with a project that already used Bazel, so if I can’t use the existing Bazel build, I’ll probably try to wrap the setup.py a Bazel rule or something.

What's the project, and how are you planning to integrate the build files?

> Unless I’m misreading the whole v2/v3 thing, is v3 available yet? 

Not yet. It's a construction field at the moment. The setup.py build on "master" will work, but the real action is happening in beancount/ccore and beancount/cparser and that's most definitely not ready to use. I still co v2 myself when I need to do accounting at the moment. I'm working on completing a core + parser entirely in C++ producing compatible Python data structure and then switch over.


> Also, it does seem to (mostly) work - on my run, all but two of the tests pass. I didn’t dig into the failing ones, but that indicates to me that the essential part of the configuration is correct.

If you run the pytest tests with the setup.py build, it should work. A bunch of code has been deleted though (for good), e.g., plugins that aren't going to survive in the core, bean-web & bean-report (deprecated in favor of Fava and bean-query), the holdings code (not needed, see net-worth-over-time.py), bean-price (moved to its own repo), and soon the ingest code too (will be moved to own repo). The resulting code on v3 will be a tight core I can realistically maintain and evolve (can't wait to write new features).

**Comment by blais** [comment]
Finally, as for the ticket, I barely tried to run on a macOS box, it would help to fixup the Bazel build for it. I probably won't have time for a while as I'm building a bunch of new stuff on Linux (Ubuntu 18.04, soon 20.04). Happy to receive a working patch though. I'll go look at the other two tickets. 

I'll leave this ticket up until Bazel build on macOS works though.

**Comment by jbeder** [comment]
My project is a finance app with a server backend; transactions are stored in beancount format in the database and the server runs queries over them using the beancount binaries (triggered from RPCs from the client). I'm writing the server in Go, and it calls the beancount binaries via the exec package. The integration works great now (with my two patches), and Bazel works well for packaging the beancount binaries into the server's runfiles.

I'm looking forward to switching over to v3 once it's ready; I think that will fit my use case even more, since I can just call the C++ library directly from Go and pass protos (if I'm reading it right?), so I won't have to mess with runfiles or shell commands.

As for this ticket: once the PRs are merged I'll post the remaining test errors, and I can try a bit to fix them if that's appropriate. Thanks for merging the linker error one.

**Comment by blais** [comment]
Awesome. Let me know if some changes or improvements would be welcome to the .bzl files; I'm not that knowledgeable with Bazel config files but managed to cobble this together. I see you used to be an SRE, maybe you know them better.  (In particular, I'm a little frustrated that there isn't generic support for python_configure and py_extension with a central, updated definition.)

See this proto for the data definition that will eventually be used:
https://github.com/beancount/beancount/blob/master/beancount/ccore/data.proto
It's still light on comments - will be beefed up like data.py - and subject to change, but that should give you an idea of better things to come, so these directives will be storable in binary formats and sendable over RPC.
