### ISSUE TITLE
bean-query barfs when comparing a position with a number

### ISSUE THREAD

**Issue by blais** [beancount/beancount#6]
**[Original report](https://bitbucket.org/blais/beancount/issue/6) by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

So I tried this

select date, narration, position balance from year=2013 where account ~ "Liabilities.*PropertyTax$" and  (position >  0.00), 

Try with "number".
The "position" column returns an object of type Position.

I've cooked a script in attachment for you.

 

but it gives me 

Traceback (most recent call last):
  File "/usr/lib/python3.4/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'BQLShell' object has no attribute 'do_select'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "usr/local/lib/python3.4/site-packages/beancount/query/shell.py", line 223, in default
    self.dispatch(statement)
  File "/usr/local/lib/python3.4/site-packages/beancount/query/shell.py", line 213, in dispatch
    return method(statement)
  File "/usr/local/lib/python3.4/site-packages/beancount/query/shell.py", line 343, in on_Select
    self.options_map)
  File "/usr/local/lib/python3.4/site-packages/beancount/query/query_execute.py", line 207, in execute_query
    if c_where is None or c_where(context):
  File "/usr/local/lib/python3.4/site-packages/beancount/query/query_compile.py", line 111, in __call__
    return self.operator(self.left(context), self.right(context))
  File "/usr/local/lib/python3.4/site-packages/beancount/query/query_compile.py", line 111, in __call__
    return self.operator(self.left(context), self.right(context))
TypeError: unorderable types: Position() > decimal.Decimal()

Uh-oh. That's clearly a bug.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Actually, that's expected. There's no type checking on operators in the SQL shell implementation, and that will be part of the next implementation (a full rewrite).
