### ISSUE TITLE
cannot install in Ubuntu 16.04

### ISSUE THREAD

**Issue by ouboub** [beancount/beancount#603]
Hi

right now it is difficult for me to upgrade my Ubuntu 16.04 distro (which ships python 3.5)
I tried out various beancount version, but I always obtain the following error:

pip3 install --user beancount==2.2.0

DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Collecting beancount==2.2.0
  Using cached beancount-2.2.0.tar.gz (597 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c7jyqi8b/beancount_75ddebbf215447ce9d81b84d4eccac3a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c7jyqi8b/beancount_75ddebbf215447ce9d81b84d4eccac3a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-2wi4v5ia
         cwd: /tmp/pip-install-c7jyqi8b/beancount_75ddebbf215447ce9d81b84d4eccac3a/
    Complete output (25 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 11, in <module>
        from setuptools.extern.six.moves import filterfalse, map
      File "/usr/lib/python3/dist-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
        @_call_aside
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
        f(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
        add_activation_listener(lambda dist: dist.activate())
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 956, in subscribe
        callback(dist)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2515, in activate
        declare_namespace(pkg)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by dnicolodi** [comment]
This does not seem to be an error generated from something going wrong in Beancount `setup.py` but a failure in initializing the `setuptools`module. I think something fundamental is broken in your Python environment. Can you install any other python package? Where is your `pip` coming from? I think Ubuntu 16.04 should have a `pip` version older than the 21.0 you are using here (it would be weird for Ubuntu to ship a `pip` version that complains about a too old Python version in relation the the Python they are distributing).

That said, I don't think there are enough resources to support any other release of Beancount that is not the latest, which is 2.3.3 at the time of writing, and requires Python 3.6. I think you can safely install a more recent Python release on Ubuntu 16.04 alongside the distribution system version.

**Comment by blais** [comment]
Just compile 3.9 from source and install in /usr/local, that's what I do.
Sorry no better answer. Not going to backport
