### ISSUE TITLE
bean-format fails due to whitespace after account name

### ISSUE THREAD

**Issue by blais** [beancount/beancount#63]
**[Original report](https://bitbucket.org/blais/beancount/issue/63) by Benjamin Weber (Bitbucket: [hyllos](https://bitbucket.org/hyllos), GitHub: [hyllos](https://github.com/hyllos)).**

----------------------------------------

```
bash-4.3$ bean-format ~/Desktop/bug.txt
Traceback (most recent call last):
  File "/usr/local/bin/bean-format", line 2, in <module>
    from beancount.scripts.format import main; main()
  File "/usr/local/lib/python3.4/site-packages/beancount/scripts/format.py", line 149, in main
    formatted_contents = align_beancount(contents)
  File "/usr/local/lib/python3.4/site-packages/beancount/scripts/format.py", line 77, in align_beancount
    re.sub(r'[ \t]+', ' ', formatted_contents.rstrip()))
AssertionError
```

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Fixed #63: Trailing whitespace would cause bean-format to fail.
