### ISSUE TITLE
Did `ingest` disappear ?

### ISSUE THREAD

**Issue by gagbo** [beancount/beancount#651]
Hello,

I installed Beancount with git on master just right now (assuming e1716b4 ), on a fresh-ish install of Fedora 34, just in `~/.local/lib/`, using `pip install --user git+https://github.com/beancount/beancount#egg=beancount`, and I installed fava using the Pypi package.

When I try to start fava (for anything, either `fava ledger.beancount` or `fava --help`) I have

```
Traceback (most recent call last):
  File "/home/gagbo/.local/bin/fava", line 5, in <module>
    from fava.cli import main
  File "/home/gagbo/.local/lib/python3.9/site-packages/fava/cli.py", line 11, in <module>
    from fava.application import app
  File "/home/gagbo/.local/lib/python3.9/site-packages/fava/application.py", line 40, in <module>
    from fava import template_filters
  File "/home/gagbo/.local/lib/python3.9/site-packages/fava/template_filters.py", line 21, in <module>
    from fava.context import g
  File "/home/gagbo/.local/lib/python3.9/site-packages/fava/context.py", line 6, in <module>
    from fava.core import FavaLedger
  File "/home/gagbo/.local/lib/python3.9/site-packages/fava/core/__init__.py", line 58, in <module>
    from fava.core.ingest import IngestModule
  File "/home/gagbo/.local/lib/python3.9/site-packages/fava/core/ingest.py", line 12, in <module>
    from beancount.ingest import cache  # type: ignore
ModuleNotFoundError: No module named 'beancount.ingest'
```

Is there anything I can do to make it work ?

Thanks for your work on beancount, it really helps me a lot

**Comment by blais** [comment]
https://github.com/beancount/beangulp
or find it in branch "v2"

**Comment by gagbo** [comment]
Oh right, so I guess I'll have to look into fava as well to make the change if I want to keep using the main branch here :) I'll see what to do then, thanks
