### ISSUE TITLE
undefined symbol: PyExceptionClass_Name when running on Pypy

### ISSUE THREAD

**Issue by ang-st** [beancount/beancount#737]
Hello, 

I wanted to give a try running beancount  2.3.5 with latest Pypy version  and get the following error at startup

```
└─[$] <> python -V
Python 3.9.12 (05fbe3aa5b0845e6c37239768aa455451aa5faba, Mar 29 2022, 08:15:34)
[PyPy 7.3.9 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]

```

```
└─[$] <> bean-check bean_files/dge-header.bean      
Traceback (most recent call last):
  File "/home/ang-st/.pyenv/versions/pypy3.9-7.3.9/bin/bean-check", line 33, in <module>
    sys.exit(load_entry_point('beancount==2.3.5', 'console_scripts', 'bean-check')())
  File "/home/ang-st/.pyenv/versions/pypy3.9-7.3.9/bin/bean-check", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/ang-st/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/ang-st/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<builtin>/frozen importlib._bootstrap_external", line 863, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ang-st/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/site-packages/beancount/scripts/check.py", line 11, in <module>
    from beancount import loader
  File "<frozen importlib._bootstrap>", line 1058, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ang-st/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/site-packages/beancount/loader.py", line 26, in <module>
    from beancount.parser import parser
  File "/home/ang-st/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/site-packages/beancount/parser/parser.py", line 119, in <module>
    from beancount.parser import _parser
  File "<frozen importlib._bootstrap>", line 1058, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: /home/ang-st/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/site-packages/beancount/parser/_parser.pypy39-pp73-x86_64-linux-gnu.so: undefined symbol: PyExceptionClass_Name
```

I tried with an earlier version  and I still get the same error.  Any chance I could make beancount running on Pypy ? 

Thank you

**Comment by dnicolodi** [comment]
It seems that for some reason the headers you used for compiling beancount define the `PyExceptionClass_Name()` function, but PyPy actually does not export it. This is weird and probably a but in your environment or in PyPy. I tried to compile beancount with PyPy 3.7 and it fails to compile because PyPy does not have a definition for `PyExceptionClass_Name()`.

You can try to stick a
```
#define PyExceptionClass_Name(x) (((PyTypeObject*)(x))->tp_name)
```
in `lexer.l` and recompile. Although, `PyExceptionClass_Name()` was used because accessing the exception object internals should in principle be less portable than using the accessor function...

**Comment by ang-st** [comment]
Thank you @dnicolodi 

I have been able to build it successfully 

```
─➤  /home/ang-st/.pyenv/shims/bean-check                                                  1 ↵
usage: bean-check [-h] [--version] [-v] [-C] [--cache-filename CACHE_FILENAME] filename
bean-check: error: the following arguments are required: filename
```

But now i  hit another bump ... 

```
/home/ang-st/.pyenv/shims/bean-check /tmp/test.bean                                   2 ↵
Traceback (most recent call last):
  File "/home/ang-st/.pyenv/versions/pypy3.9-7.3.9/bin/bean-check", line 33, in <module>
    sys.exit(load_entry_point('beancount==2.3.5', 'console_scripts', 'bean-check')())
  File "/home/ang-st/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/site-packages/beancount-2.3.5-py3.9-linux-x86_64.egg/beancount/scripts/check.py", line 49, in main
    entries, errors, _ = loader.load_file(
  File "/home/ang-st/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/site-packages/beancount-2.3.5-py3.9-linux-x86_64.egg/beancount/loader.py", line 90, in load_file
    entries, errors, options_map = _load_file(
  File "/home/ang-st/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/site-packages/beancount-2.3.5-py3.9-linux-x86_64.egg/beancount/loader.py", line 215, in wrapped
    result = function(toplevel_filename, *args, **kw)
  File "/home/ang-st/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/site-packages/beancount-2.3.5-py3.9-linux-x86_64.egg/beancount/loader.py", line 256, in _uncached_load_file
    return _load([(filename, True)], *args, **kw)
  File "/home/ang-st/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/site-packages/beancount-2.3.5-py3.9-linux-x86_64.egg/beancount/loader.py", line 501, in _load
    entries, parse_errors, options_map = _parse_recursive(
  File "/home/ang-st/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/site-packages/beancount-2.3.5-py3.9-linux-x86_64.egg/beancount/loader.py", line 395, in _parse_recursive
    src_options_map) = parser.parse_file(filename, encoding=encoding)
  File "/home/ang-st/.pyenv/versions/pypy3.9-7.3.9/lib/pypy3.9/site-packages/beancount-2.3.5-py3.9-linux-x86_64.egg/beancount/parser/parser.py", line 202, in parse_file
    parser.parse(file, filename=report_filename, lineno=report_firstline, **kw)
TypeError: a read-write bytes-like object is required, not memoryview
```

**Comment by dnicolodi** [comment]
The issue comes from this code https://github.com/beancount/beancount/blob/8d4220ba44b3a413ea5da345af318eeb829daf11/beancount/parser/lexer.l#L443-L451 which as far as I can tell is perfectly correct.  Apparently PyPy does not like the fact that the `readinto()` argument is a memory view object and not a bytes object. I think the PyPy implementation of file objects `readinto()` method is broken, or at least it does not behave accordingly to the documentation https://docs.python.org/3/library/io.html#io.RawIOBase.readinto

**Comment by dnicolodi** [comment]
See #738

**Comment by blais** [comment]
AFAIK Beancount was never compiled with PyPy.

**Comment by dnicolodi** [comment]
Well, now it has 😃 There are 7 test failures on PyPy 3.7, but they all look like false positives.

**Comment by ang-st** [comment]
awesome 👍 I'll give a try today 
Thanks again
