### ISSUE TITLE
bean-identify, bean-extract commands do not work with beancount file

### ISSUE THREAD

**Issue by uzkikh** [beancount/beancount#801]
I have importers configured for different data sources. I haven't run imports for a week and a half. Today I faced a problem running the bean-identify and bean-extract utilities to update my transaction journal. Perhaps during this time, some updates were installed on the system that broke this functionality.
As a result of running, I get the following traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/bean-identify", line 8, in <module>
    sys.exit(identify_main())
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/beancount/ingest/scripts_utils.py", line 31, in identify_main
    return trampoline_to_ingest(identify)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/beancount/ingest/scripts_utils.py", line 198, in trampoline_to_ingest
    return run_import_script_and_ingest(parser)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/beancount/ingest/scripts_utils.py", line 234, in run_import_script_and_ingest
    mod = runpy.run_path(args.config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 285, in run_path
  File "<frozen runpy>", line 259, in _get_code_from_file
  File "journal.beancount", line 20
    2022-01-01 custom "fava-option" "show-accounts-with-zero-balance" "false"
         ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
```

**Comment by dnicolodi** [comment]
I'm pretty sure you are running the wrong command line: it seems that beancount is trying to run your ledger as a Python script as it were the import script. However, no enough details are provided to be sure that this is the case.

**Comment by uzkikh** [comment]
@dnicolodi, thank you. You are right. I used the wrong command. I forgot the syntax, but I was sure it was correct.
