### ISSUE TITLE
sorting postings raises AttributeError: posting_sortkey() does not really support Postings

### ISSUE THREAD

**Issue by castilma** [beancount/beancount#887]
When I try to sort a list of Posting objects, I get an AttributeError: 

```
$ bean-extract import.config  2024-12-1-gnucash.csv 
ERROR:root:Importer gnucash.extract() raised an unexpected error: 'Posting' object has no attribute 'date'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/beancount/ingest/extract.py", line 182, in extract
    new_entries = extract_from_file(
                  ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/beancount/ingest/extract.py", line 67, in extract_from_file
    new_entries = importer.extract(file, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mcd/Dokumente/finanzen/bean/importers/gnucash.py", line 214, in extract
    postings.sort(key=posting_sortkey)
  File "/usr/lib/python3.12/site-packages/beancount/core/data.py", line 615, in posting_sortkey
    return (entry.date, SORT_ORDER.get(type(entry), 0), entry.meta["lineno"])
            ^^^^^^^^^^
AttributeError: 'Posting' object has no attribute 'date'
```
I understand from the docstring that posting_sortkey() is for Postings, too, but the implementation looks like it's only for Entries and txnPostings.
I want to sort the Postings belonging to the same transaction, according to account type. Do I need to write my own sortkey function?

**Comment by blais** [comment]
There should be an assert, this is not intended to sort postings. Error in gnucash.

**Comment by blais** [comment]
Oh my the docs are wrong here. There's a bug in Beancount. Will fix.
